//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AE_TnN_Mobile_V001.GenerateDocument {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenerateDocument.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AE_TnN_Mobile_V001.GenerateDocument.HelloWorldResponse HelloWorld(AE_TnN_Mobile_V001.GenerateDocument.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ItemCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenDoc", ReplyAction="*")]
        AE_TnN_Mobile_V001.GenerateDocument.GenDocResponse GenDoc(AE_TnN_Mobile_V001.GenerateDocument.GenDocRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AE_TnN_Mobile_V001.GenerateDocument.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AE_TnN_Mobile_V001.GenerateDocument.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_TnN_Mobile_V001.GenerateDocument.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AE_TnN_Mobile_V001.GenerateDocument.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenDoc", Namespace="http://tempuri.org/", Order=0)]
        public AE_TnN_Mobile_V001.GenerateDocument.GenDocRequestBody Body;
        
        public GenDocRequest() {
        }
        
        public GenDocRequest(AE_TnN_Mobile_V001.GenerateDocument.GenDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ItemCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CaseNumber;
        
        public GenDocRequestBody() {
        }
        
        public GenDocRequestBody(string ItemCode, string CaseNumber) {
            this.ItemCode = ItemCode;
            this.CaseNumber = CaseNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public AE_TnN_Mobile_V001.GenerateDocument.GenDocResponseBody Body;
        
        public GenDocResponse() {
        }
        
        public GenDocResponse(AE_TnN_Mobile_V001.GenerateDocument.GenDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenDocResult;
        
        public GenDocResponseBody() {
        }
        
        public GenDocResponseBody(string GenDocResult) {
            this.GenDocResult = GenDocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : AE_TnN_Mobile_V001.GenerateDocument.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<AE_TnN_Mobile_V001.GenerateDocument.Service1Soap>, AE_TnN_Mobile_V001.GenerateDocument.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_TnN_Mobile_V001.GenerateDocument.HelloWorldResponse AE_TnN_Mobile_V001.GenerateDocument.Service1Soap.HelloWorld(AE_TnN_Mobile_V001.GenerateDocument.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AE_TnN_Mobile_V001.GenerateDocument.HelloWorldRequest inValue = new AE_TnN_Mobile_V001.GenerateDocument.HelloWorldRequest();
            inValue.Body = new AE_TnN_Mobile_V001.GenerateDocument.HelloWorldRequestBody();
            AE_TnN_Mobile_V001.GenerateDocument.HelloWorldResponse retVal = ((AE_TnN_Mobile_V001.GenerateDocument.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AE_TnN_Mobile_V001.GenerateDocument.GenDocResponse AE_TnN_Mobile_V001.GenerateDocument.Service1Soap.GenDoc(AE_TnN_Mobile_V001.GenerateDocument.GenDocRequest request) {
            return base.Channel.GenDoc(request);
        }
        
        public string GenDoc(string ItemCode, string CaseNumber) {
            AE_TnN_Mobile_V001.GenerateDocument.GenDocRequest inValue = new AE_TnN_Mobile_V001.GenerateDocument.GenDocRequest();
            inValue.Body = new AE_TnN_Mobile_V001.GenerateDocument.GenDocRequestBody();
            inValue.Body.ItemCode = ItemCode;
            inValue.Body.CaseNumber = CaseNumber;
            AE_TnN_Mobile_V001.GenerateDocument.GenDocResponse retVal = ((AE_TnN_Mobile_V001.GenerateDocument.Service1Soap)(this)).GenDoc(inValue);
            return retVal.Body.GenDocResult;
        }
    }
}
